theme = "github_dark"
[keys.normal]
A-S-f = ":format"
[keys.insert]
[keys.select]
[editor]
cursorline = true
rulers = [80]
bufferline = "always"
[editor.lsp]
[editor.indent-guides]
render = false
[editor.soft-wrap]
enable = true
