[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "Poetry.lock", ".git"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
auto-format = true
formatter = {command = 'black', args = ["--quiet", "-"]}
config = ""

[[language]]
name = "markdown"
language-server = { command = "/home/jay/Documents/Programs/ltex-ls/bin/ltex-ls" }
file-types = ["md", "txt"]
scope = "source.markdown"
roots = []

[[language]]
name = "rust"

[language.config]
checkOnSave = { command = "clippy" }

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "0431a2c60828731f27491ee9fdefe25e250ce9c9" }