classic: false

blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

color:
  when: auto
  theme: default

date: date

dereference: false

icons:
  when: auto
  theme: fancy
  separator: " "

indicators: false

layout: tree

recursion:
  enabled: false
  depth: 1

size: default

permission: rwx

sorting:
  column: name
  reverse: false
  dir-grouping: none

no-symlink: false

total-size: false

hyperlink: never

symlink-arrow: ⇒

header: false